export const ZONES = [
  {
    id: 1,
    title: "СТАНДАРТ",
    images: ["/images/zones/standard1.jpg"],
    feature: "Игровой ПК и перефирия",
    subtitle: "Общая зона",
    color: "#e637b7",
    characteristics: [
      {
        id: 1,
        title: "процессор",
        value: "AMD Ryzen 7 2700X",
        image: "/images/characteristics/01.svg",
      },
      {
        id: 2,
        title: "видеокарта",
        value: "GeForce GTX 1080",
        image: "/images/characteristics/02.svg",
      },
      {
        id: 3,
        title: "память",
        value: "DDR4 16GB",
        image: "/images/characteristics/03.svg",
      },
      {
        id: 4,
        title: "накопитель",
        value: "NVMe SSD",
        image: "/images/characteristics/04.svg",
      },
      {
        id: 5,
        title: "монитор",
        value: '"27" 144Hz',
        image: "/images/characteristics/05.svg",
      },
      {
        id: 6,
        title: "клавиатура",
        value: "Gamdias Hermes E2",
        image: "/images/characteristics/06.svg",
      },
      {
        id: 7,
        title: "мышка",
        value: "Logitech G403",
        image: "/images/characteristics/07.svg",
      },
      {
        id: 8,
        title: "наушники",
        value: "Corsair HS50",
        image: "/images/characteristics/08.svg",
      },
    ],
    prices: [
      {
        id: 1,
        title: "Тариф «1 Час»",
        available: "Доступен 24/7",
        image: "/images/icons/1h.svg",
        rate: "Стандартный тариф",
        price: 140,
        borderColor: "#feceec",
      },
      {
        id: 2,
        title: "Тариф «3 Часа»",
        available: "Доступен 24/7",
        image: "/images/icons/3h.svg",
        rate: "Выгода: Час = 130 ₽ ",
        price: 390,
        borderColor: "#fe7ccd",
      },
      {
        id: 3,
        title: "Тариф «5 Часов»",
        available: "Доступен 24/7",
        image: "/images/icons/5h.svg",
        rate: "Выгода: Час = 100 ₽ ",
        price: 490,
        borderColor: "#ff7dcd",
      },
      {
        id: 4,
        title: "Тариф «7 Часов»",
        available: "Доступен 24/7",
        image: "/images/icons/7h.svg",
        rate: "Выгода: Час = 85 ₽ ",
        price: 590,
        borderColor: "#fe5dc1",
      },
      {
        id: 5,
        title: "Тариф «Ночь»",
        available: "23:00 ‒ 10:00",
        image: "/images/icons/night.svg",
        rate: "Выгода: Час = 65 ₽ ",
        price: 690,
        borderColor: "#ff40b6",
      },
      {
        id: 6,
        title: "Тариф «День»",
        available: "10:00 ‒ 23:00",
        image: "/images/icons/day.svg",
        rate: "Выгода: Час = 60 ₽ ",
        price: 790,
        borderColor: "#ff0aa2",
      },
    ],
  },
  {
    id: 2,
    title: "Стандарт+",
    images: ["/images/zones/standard-plus1.jpg"],
    feature: "Монитор больше + ПК мощнее",
    subtitle: "Лучшие Места",
    color: "#149ef2",
    characteristics: [
      {
        id: 1,
        title: "процессор",
        value: "AMD Ryzen 7 2700X",
        image: "/images/characteristics/01.svg",
      },
      {
        id: 2,
        title: "видеокарта",
        value: "GeForce GTX 1080",
        image: "/images/characteristics/02.svg",
      },
      {
        id: 3,
        title: "память",
        value: "DDR4 16GB",
        image: "/images/characteristics/03.svg",
      },
      {
        id: 4,
        title: "накопитель",
        value: "NVMe SSD",
        image: "/images/characteristics/04.svg",
      },
      {
        id: 5,
        title: "монитор",
        value: '"27" 144Hz',
        image: "/images/characteristics/05.svg",
      },
      {
        id: 6,
        title: "клавиатура",
        value: "Gamdias Hermes E2",
        image: "/images/characteristics/06.svg",
      },
      {
        id: 7,
        title: "мышка",
        value: "Logitech G403",
        image: "/images/characteristics/07.svg",
      },
      {
        id: 8,
        title: "наушники",
        value: "Corsair HS50",
        image: "/images/characteristics/08.svg",
      },
    ],
    prices: [
      {
        id: 1,
        title: "Тариф «1 Час»",
        available: "Доступен 24/7",
        image: "/images/icons/1h.svg",
        rate: "Стандартный тариф",
        price: 140,
        borderColor: "#eef9ff",
      },
      {
        id: 2,
        title: "Тариф «3 Часа»",
        available: "Доступен 24/7",
        image: "/images/icons/3h.svg",
        rate: "Выгода: Час = 130 ₽ ",
        price: 390,
        borderColor: "#b2e2ff",
      },
      {
        id: 3,
        title: "Тариф «5 Часов»",
        available: "Доступен 24/7",
        image: "/images/icons/5h.svg",
        rate: "Выгода: Час = 100 ₽ ",
        price: 490,
        borderColor: "#3ea8f1",
      },
      {
        id: 4,
        title: "Тариф «7 Часов»",
        available: "Доступен 24/7",
        image: "/images/icons/7h.svg",
        rate: "Выгода: Час = 85 ₽ ",
        price: 590,
        borderColor: "#72caff",
      },
      {
        id: 5,
        title: "Тариф «Ночь»",
        available: "23:00 ‒ 10:00",
        image: "/images/icons/night.svg",
        rate: "Выгода: Час = 65 ₽ ",
        price: 690,
        borderColor: "#1c9bf1",
      },
      {
        id: 6,
        title: "Тариф «День»",
        available: "10:00 ‒ 23:00",
        image: "/images/icons/day.svg",
        rate: "Выгода: Час = 60 ₽ ",
        price: 790,
        borderColor: "#1da9fe",
      },
    ],
  },
  {
    id: 3,
    title: "ПРИСТАВКА",
    images: ["/images/zones/ps1.jpg"],
    feature: "Подписка PS+ и 2 геймпада",
    subtitle: "Диван + PS5",
    color: "#2636c0",
    characteristics: [],
    prices: [
      {
        id: 1,
        title: "Тариф «1 Час»",
        available: "Доступен 24/7",
        image: "/images/icons/1h.svg",
        rate: "Стандартный тариф",
        price: 140,
        borderColor: "#444759",
      },
      {
        id: 2,
        title: "Тариф «3 Часа»",
        available: "Доступен 24/7",
        image: "/images/icons/3h.svg",
        rate: "Выгода: Час = 130 ₽ ",
        price: 390,
        borderColor: "#434da2",
      },
      {
        id: 3,
        title: "Тариф «5 Часов»",
        available: "Доступен 24/7",
        image: "/images/icons/5h.svg",
        rate: "Выгода: Час = 100 ₽ ",
        price: 490,
        borderColor: "#3544b8",
      },
    ],
  },
  {
    id: 4,
    title: "BOOT CAMP",
    images: ["/images/zones/bc1.jpg"],
    feature: "На 5 или 10 мест + лучшие ПК",
    subtitle: "Отдельная Комната",
    color: "#ff003d",
    characteristics: [
      {
        id: 1,
        title: "процессор",
        value: "AMD Ryzen 7 2700X",
        image: "/images/characteristics/01.svg",
      },
      {
        id: 2,
        title: "видеокарта",
        value: "GeForce GTX 1080",
        image: "/images/characteristics/02.svg",
      },
      {
        id: 3,
        title: "память",
        value: "DDR4 16GB",
        image: "/images/characteristics/03.svg",
      },
      {
        id: 4,
        title: "накопитель",
        value: "NVMe SSD",
        image: "/images/characteristics/04.svg",
      },
      {
        id: 5,
        title: "монитор",
        value: '"27" 144Hz',
        image: "/images/characteristics/05.svg",
      },
      {
        id: 6,
        title: "клавиатура",
        value: "Gamdias Hermes E2",
        image: "/images/characteristics/06.svg",
      },
      {
        id: 7,
        title: "мышка",
        value: "Logitech G403",
        image: "/images/characteristics/07.svg",
      },
      {
        id: 8,
        title: "наушники",
        value: "Corsair HS50",
        image: "/images/characteristics/08.svg",
      },
    ],
    prices: [
      {
        id: 1,
        title: "Тариф «1 Час»",
        available: "Доступен 24/7",
        image: "/images/icons/1h.svg",
        rate: "Стандартный тариф",
        price: 140,
        borderColor: "#ffd2dc",
      },
      {
        id: 2,
        title: "Тариф «3 Часа»",
        available: "Доступен 24/7",
        image: "/images/icons/3h.svg",
        rate: "Выгода: Час = 130 ₽ ",
        price: 390,
        borderColor: "#ffa2b8",
      },
      {
        id: 3,
        title: "Тариф «5 Часов»",
        available: "Доступен 24/7",
        image: "/images/icons/5h.svg",
        rate: "Выгода: Час = 100 ₽ ",
        price: 490,
        borderColor: "#e37d95",
      },
      {
        id: 4,
        title: "Тариф «7 Часов»",
        available: "Доступен 24/7",
        image: "/images/icons/7h.svg",
        rate: "Выгода: Час = 85 ₽ ",
        price: 590,
        borderColor: "#fe5a82",
      },
      {
        id: 5,
        title: "Тариф «Ночь»",
        available: "23:00 ‒ 10:00",
        image: "/images/icons/night.svg",
        rate: "Выгода: Час = 65 ₽ ",
        price: 690,
        borderColor: "#ff3364",
      },
      {
        id: 6,
        title: "Тариф «День»",
        available: "10:00 ‒ 23:00",
        image: "/images/icons/day.svg",
        rate: "Выгода: Час = 60 ₽ ",
        price: 790,
        borderColor: "#ff144c",
      },
    ],
  },
];
