export const ZONES = [
  {
    id: 1,
    title: "СТАНДАРТ",
    images: ["/images/zones/standard1.jpg"],
    feature: "Игровой ПК и перефирия",
    subtitle: "Общая зона",
    color: "#e637b7",
    characteristics: [
      {
        id: 1,
        title: "процессор",
        value: "AMD Ryzen 7 2700X",
        image: "/images/characteristics/01.svg",
      },
      {
        id: 2,
        title: "видеокарта",
        value: "GeForce GTX 1080",
        image: "/images/characteristics/02.svg",
      },
      {
        id: 3,
        title: "память",
        value: "DDR4 16GB",
        image: "/images/characteristics/03.svg",
      },
      {
        id: 4,
        title: "накопитель",
        value: "NVMe SSD",
        image: "/images/characteristics/04.svg",
      },
      {
        id: 5,
        title: "монитор",
        value: '"27" 144Hz',
        image: "/images/characteristics/05.svg",
      },
      {
        id: 6,
        title: "клавиатура",
        value: "Gamdias Hermes E2",
        image: "/images/characteristics/06.svg",
      },
      {
        id: 7,
        title: "мышка",
        value: "Logitech G403",
        image: "/images/characteristics/07.svg",
      },
      {
        id: 8,
        title: "наушники",
        value: "Corsair HS50",
        image: "/images/characteristics/08.svg",
      },
    ],
    prices: [
      {
        id: 1,
        title: "Тариф «1 Час»",
        available: "Доступен 24/7",
        image: "/image/zones/1h.svg",
        rate: "Стандартный тариф",
        price: 140,
      },
      {
        id: 2,
        title: "Тариф «3 Часа»",
        available: "Доступен 24/7",
        image: "/image/zones/3h.svg",
        rate: "Выгода: Час = 130 ₽ ",
        price: 390,
      },
      {
        id: 3,
        title: "Тариф «5 Часов»",
        available: "Доступен 24/7",
        image: "/image/zones/5h.svg",
        rate: "Выгода: Час = 100 ₽ ",
        price: 490,
      },
      {
        id: 4,
        title: "Тариф «7 Часов»",
        available: "Доступен 24/7",
        image: "/image/zones/1h.svg",
        rate: "Выгода: Час = 85 ₽ ",
        price: 590,
      },
      {
        id: 5,
        title: "Тариф «Ночь»",
        available: "23:00 ‒ 10:00",
        image: "/image/zones/night.svg",
        rate: "Выгода: Час = 65 ₽ ",
        price: 690,
      },
      {
        id: 6,
        title: "Тариф «День»",
        available: "10:00 ‒ 23:00",
        image: "/image/zones/day.svg",
        rate: "Выгода: Час = 60 ₽ ",
        price: 790,
      },
    ],
  },
  {
    id: 2,
    title: "Стандарт+",
    images: ["/images/zones/standard-plus1.jpg"],
    feature: "Монитор больше + ПК мощнее",
    subtitle: "Лучшие Места",
    color: "#149ef2",
    characteristics: [
      {
        id: 1,
        title: "процессор",
        value: "AMD Ryzen 7 2700X",
        image: "/images/characteristics/01.svg",
      },
      {
        id: 2,
        title: "видеокарта",
        value: "GeForce GTX 1080",
        image: "/images/characteristics/02.svg",
      },
      {
        id: 3,
        title: "память",
        value: "DDR4 16GB",
        image: "/images/characteristics/03.svg",
      },
      {
        id: 4,
        title: "накопитель",
        value: "NVMe SSD",
        image: "/images/characteristics/04.svg",
      },
      {
        id: 5,
        title: "монитор",
        value: '"27" 144Hz',
        image: "/images/characteristics/05.svg",
      },
      {
        id: 6,
        title: "клавиатура",
        value: "Gamdias Hermes E2",
        image: "/images/characteristics/06.svg",
      },
      {
        id: 7,
        title: "мышка",
        value: "Logitech G403",
        image: "/images/characteristics/07.svg",
      },
      {
        id: 8,
        title: "наушники",
        value: "Corsair HS50",
        image: "/images/characteristics/08.svg",
      },
    ],
    prices: [
      {
        id: 1,
        title: "Тариф «1 Час»",
        available: "Доступен 24/7",
        image: "/image/zones/1h.svg",
        rate: "Стандартный тариф",
        price: 140,
      },
      {
        id: 2,
        title: "Тариф «3 Часа»",
        available: "Доступен 24/7",
        image: "/image/zones/3h.svg",
        rate: "Выгода: Час = 130 ₽ ",
        price: 390,
      },
      {
        id: 3,
        title: "Тариф «5 Часов»",
        available: "Доступен 24/7",
        image: "/image/zones/5h.svg",
        rate: "Выгода: Час = 100 ₽ ",
        price: 490,
      },
      {
        id: 4,
        title: "Тариф «7 Часов»",
        available: "Доступен 24/7",
        image: "/image/zones/1h.svg",
        rate: "Выгода: Час = 85 ₽ ",
        price: 590,
      },
      {
        id: 5,
        title: "Тариф «Ночь»",
        available: "23:00 ‒ 10:00",
        image: "/image/zones/night.svg",
        rate: "Выгода: Час = 65 ₽ ",
        price: 690,
      },
      {
        id: 6,
        title: "Тариф «День»",
        available: "10:00 ‒ 23:00",
        image: "/image/zones/day.svg",
        rate: "Выгода: Час = 60 ₽ ",
        price: 790,
      },
    ],
  },
  {
    id: 3,
    title: "ПРИСТАВКА",
    images: ["/images/zones/ps1.jpg"],
    feature: "Подписка PS+ и 2 геймпада",
    subtitle: "Диван + PS5",
    color: "#2636c0",
    characteristics: [
      {
        id: 1,
        title: "процессор",
        value: "AMD Ryzen 7 2700X",
        image: "/images/characteristics/01.svg",
      },
      {
        id: 2,
        title: "видеокарта",
        value: "GeForce GTX 1080",
        image: "/images/characteristics/02.svg",
      },
      {
        id: 3,
        title: "память",
        value: "DDR4 16GB",
        image: "/images/characteristics/03.svg",
      },
      {
        id: 4,
        title: "накопитель",
        value: "NVMe SSD",
        image: "/images/characteristics/04.svg",
      },
      {
        id: 5,
        title: "монитор",
        value: '"27" 144Hz',
        image: "/images/characteristics/05.svg",
      },
      {
        id: 6,
        title: "клавиатура",
        value: "Gamdias Hermes E2",
        image: "/images/characteristics/06.svg",
      },
      {
        id: 7,
        title: "мышка",
        value: "Logitech G403",
        image: "/images/characteristics/07.svg",
      },
      {
        id: 8,
        title: "наушники",
        value: "Corsair HS50",
        image: "/images/characteristics/08.svg",
      },
    ],
    prices: [
      {
        id: 1,
        title: "Тариф «1 Час»",
        available: "Доступен 24/7",
        image: "/image/zones/1h.svg",
        rate: "Стандартный тариф",
        price: 140,
      },
      {
        id: 2,
        title: "Тариф «3 Часа»",
        available: "Доступен 24/7",
        image: "/image/zones/3h.svg",
        rate: "Выгода: Час = 130 ₽ ",
        price: 390,
      },
      {
        id: 3,
        title: "Тариф «5 Часов»",
        available: "Доступен 24/7",
        image: "/image/zones/5h.svg",
        rate: "Выгода: Час = 100 ₽ ",
        price: 490,
      },
      {
        id: 4,
        title: "Тариф «7 Часов»",
        available: "Доступен 24/7",
        image: "/image/zones/1h.svg",
        rate: "Выгода: Час = 85 ₽ ",
        price: 590,
      },
      {
        id: 5,
        title: "Тариф «Ночь»",
        available: "23:00 ‒ 10:00",
        image: "/image/zones/night.svg",
        rate: "Выгода: Час = 65 ₽ ",
        price: 690,
      },
      {
        id: 6,
        title: "Тариф «День»",
        available: "10:00 ‒ 23:00",
        image: "/image/zones/day.svg",
        rate: "Выгода: Час = 60 ₽ ",
        price: 790,
      },
    ],
  },
  {
    id: 4,
    title: "BOOT CAMP",
    images: ["/images/zones/bc1.jpg"],
    feature: "На 5 или 10 мест + лучшие ПК",
    subtitle: "Отдельная Комната",
    color: "#ff003d",
    characteristics: [
      {
        id: 1,
        title: "процессор",
        value: "AMD Ryzen 7 2700X",
        image: "/images/characteristics/01.svg",
      },
      {
        id: 2,
        title: "видеокарта",
        value: "GeForce GTX 1080",
        image: "/images/characteristics/02.svg",
      },
      {
        id: 3,
        title: "память",
        value: "DDR4 16GB",
        image: "/images/characteristics/03.svg",
      },
      {
        id: 4,
        title: "накопитель",
        value: "NVMe SSD",
        image: "/images/characteristics/04.svg",
      },
      {
        id: 5,
        title: "монитор",
        value: '"27" 144Hz',
        image: "/images/characteristics/05.svg",
      },
      {
        id: 6,
        title: "клавиатура",
        value: "Gamdias Hermes E2",
        image: "/images/characteristics/06.svg",
      },
      {
        id: 7,
        title: "мышка",
        value: "Logitech G403",
        image: "/images/characteristics/07.svg",
      },
      {
        id: 8,
        title: "наушники",
        value: "Corsair HS50",
        image: "/images/characteristics/08.svg",
      },
    ],
    prices: [
      {
        id: 1,
        title: "Тариф «1 Час»",
        available: "Доступен 24/7",
        image: "/image/zones/1h.svg",
        rate: "Стандартный тариф",
        price: 140,
      },
      {
        id: 2,
        title: "Тариф «3 Часа»",
        available: "Доступен 24/7",
        image: "/image/zones/3h.svg",
        rate: "Выгода: Час = 130 ₽ ",
        price: 390,
      },
      {
        id: 3,
        title: "Тариф «5 Часов»",
        available: "Доступен 24/7",
        image: "/image/zones/5h.svg",
        rate: "Выгода: Час = 100 ₽ ",
        price: 490,
      },
      {
        id: 4,
        title: "Тариф «7 Часов»",
        available: "Доступен 24/7",
        image: "/image/zones/1h.svg",
        rate: "Выгода: Час = 85 ₽ ",
        price: 590,
      },
      {
        id: 5,
        title: "Тариф «Ночь»",
        available: "23:00 ‒ 10:00",
        image: "/image/zones/night.svg",
        rate: "Выгода: Час = 65 ₽ ",
        price: 690,
      },
      {
        id: 6,
        title: "Тариф «День»",
        available: "10:00 ‒ 23:00",
        image: "/image/zones/day.svg",
        rate: "Выгода: Час = 60 ₽ ",
        price: 790,
      },
    ],
  },
];
